### ISSUE TITLE
Section numbering is missing

### ISSUE THREAD

**Issue by studiawan** [lauritzsh/pandoc-markdown-template#4]
I have compiled the report-bib source successfully. However, section number in the PDF output is missing. 
![toc](https://cloud.githubusercontent.com/assets/1132921/20698573/7ff45ff4-b634-11e6-8931-917b7a1bbd42.png)

Do you have any idea how to solve this?
Thank you.

**Comment by lauritzsh** [comment]
What system are you on (OS, LaTeX, Pandoc version)? Have you changed anything in the `template.tex` file? At the bottom of it there is

```tex
% Chapter: 0, section: 1, subsection: 2 etc
\setcounter{secnumdepth}{1}
\setcounter{tocdepth}{1}
\tableofcontents
```

Perhaps you could try to change that `1` to a `2` and see if you are getting your sections then? It's typesetting fine for me with sections too from a fresh clone (on macOS, XeTeX 3.14159265-2.6-0.99996, pandoc 1.18).

**Comment by studiawan** [comment]
This is description of my system:
OS: Linux Mint 17 Qiana (3.13.0-24-generic #47-Ubuntu)
XaTeX: XeTeX, Version 3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
Pandoc: pandoc 1.12.2.1

Below is the result of changing variable from 1 to 2 in `template.tex`:
![toc](https://cloud.githubusercontent.com/assets/1132921/20752850/0c6fdcfe-b736-11e6-9739-f861def4d55a.png)

I notice that my Pandoc version is too old compared with yours. Is this the root of the issue?
Thank you.

**Comment by lauritzsh** [comment]
Try to upgrade first and see if that fixes it. It looks like on your system `##` is getting treated as subsection rather than a section. If upgrading does _not_ fix it, try to remove a single `#` character from all headers.

* `##` becomes `#`
* `###` becomes `##`
* etc

What I mean is that `##` should be a section but it looks like on your system it is a subsection (usually `###`). Maybe using `#` instead of `##` will let Pandoc treat it as a section. I hope it's just an outdated Pandoc that is the case.

Please see #1 and #2 as it seems related to this.

**Comment by studiawan** [comment]
I have upgraded pandoc to version 1.18 and it is now working like a charm.
Thank you for creating a beautiful template 👍
