### ISSUE TITLE
Figures appearing in the middle of the bibliography, how to prevent his whilst maintaining figure caption.

### ISSUE THREAD

**Issue by linamnt** [lauritzsh/pandoc-markdown-template#5]
Hi there. This repository is great! However, I'm having some trouble forcing the image to be in a certain location without losing the figure caption? I was trying 
```
Some Text
![alt text](link)
\ 
Some Text
```
in order to force the location to be where it is in the markdown, but then lost the caption. 

Any help would be great.

Thanks!

**Comment by lauritzsh** [comment]
As I understand the image ends up in your bibliography and you want to prevent that but do you just want to prevent it showing up in bibliography or is it important to specify exactly where it should be?

For the former could you try and see if adding `\usepackage[section]{placeins}` to `template.tex` will fix that? Your problem seems related to [this](https://tex.stackexchange.com/questions/279/how-do-i-ensure-that-figures-appear-in-the-section-theyre-associated-with) so hopefully that should fix it.

If it does fix it I will update the `template.tex` files with this package so let me know if it worked for you. :-)

**Comment by linamnt** [comment]
No it's more important that it's not in the bibliography. I was trying to fix location to prevent that but not because I needed to. Your solution works! Thanks :+1:
